name: Sample workflow
on:
  push:
    branches:
      - master
env:
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}}
jobs:
  build-and-push-dockerImage:
    runs-on: ubuntu-latest
    env:
      ENV_VAR: hello-world
      SECOND_VAR: hello-world
    steps:
      - name: Checkout out current code using public action
        uses: actions/checkout@v2
      - name: Get the list of files in our current directory
        run: |
          pwd
          ls
      - name: Build docker image
        run: |
          docker build -t nodeapp .
      - name: Login to docker
        run: |
          docker login --username $USERNAME --password $PASSWORD
      - name: Tag docker image
        run: |
          docker tag nodeapp:latest $USERNAME/nodeapp:latest
      - name: Push to docker
        run: |
          docker push $USERNAME/nodeapp:latest
      - name: Logout docker
        run: |
          docker logout
