name: Sample workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      ENV_VAR: hello-world
      SECOND_VAR: hello-world
    steps:
      - name: Checkout out current code using public action
        uses: actions/checkout@v2
      - name: Get the list of files in our current directory
        run: |
          pwd
          ls
      - name: Build docker image
        run: |
          docker build -t nodeapp .
